### ISSUE TITLE
P2P replication

### ISSUE THREAD

**Issue by deefactorial** [couchbase/couchbase-lite-android-liteserv#23]
How do clients provide P2P replication with this library ?

It seems like the application has to provide the routing to connect the client's together first before the replication can happen. What is the standardized way to connect clients to each other ? UDP broadcast ? scan the network for who is listening on open 5984 port ? I'm a little confused about this step can anyone point me in the right direction ?

Thank you,
Dominique

**Comment by sjehuda** [comment]
XEP-0174 would be a good choice!

- Ruby
https://github.com/matsadler/ahoy

- Java
https://github.com/ceefour/bonjour-quick
https://github.com/igniterealtime/Smack/pull/25
