### ISSUE TITLE
how do i login couchbase-lite-android-liteserv

### ISSUE THREAD

**Issue by DylanLyu** [couchbase/couchbase-lite-android-liteserv#26]
how do i login couchbase-lite-android-liteserv???

I do not know user name and password....

**Comment by hideki** [comment]
Hi @DylanLyu,
couchbase-lite-android-liteserv is usually used for REST API that is accessed from PhoneGap/Cordova app.

**Comment by DylanLyu** [comment]
hi @hideki ,
I know, but access couchbase-lite-android-liteserv what settings Or accessed directly on it ??

**Comment by hideki** [comment]
You can customize following lines.
https://github.com/couchbase/couchbase-lite-android-liteserv/blob/master/couchbase-lite-android-liteserv/src/main/java/com/couchbase/liteservandroid/MainActivity.java#L82-L90

If you prefer no username and no password, just call `allowedCredentials = new Credentials("", "");`
