### ISSUE TITLE
Allow this project to be imported via gradle

### ISSUE THREAD

**Issue by djensen47** [couchbase/couchbase-lite-android-liteserv#32]
This seems like it would be super useful for a debug build "flavor" on Android. But if I'm already using gradle to use Couchbase Lite in my project, how can I use this? It would be nice if there were simply a gradle dependency that I could include, which would handle all related dependencies.

**Comment by hideki** [comment]
Hi @djensen47,

If you want to use Couchbase Lite for Android, you just need to add following in build.gradle.
```
compile 'com.couchbase.lite:couchbase-lite-android:1.1.0'
```
https://github.com/couchbaselabs/GrocerySync-Android/blob/master/GrocerySync-Android/build.gradle#L42

**Comment by djensen47** [comment]
Yeah, I'm already doing that in my project. ☺ What I'm looking for it's an
easy way to add liteserv for debugging.

**Comment by hideki** [comment]
LiteServ is Android application, and it contains libraries as a submodule.If you open it with AndroidStudio, you can debug LiteServ and Couchbase Lite modules.
