### ISSUE TITLE
Change build configuration to not use .m2 local repository

### ISSUE THREAD

**Issue by michaelkwok** [couchbase/couchbase-lite-android-liteserv#36]
The build would break if .m2 is stale or not properly updated.  See issue [https://github.com/couchbase/couchbase-lite-android/issues/871](url)

**Comment by hideki** [comment]
@michaelkwok,
It seems no configuration option to disable to check the  LocalMaven. This might not be able to fix.

Disallowing to store to LocalMaven from couchbase-lite-android build could be right approach.
